#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['flask_session',
 'flask_session.cachelib',
 'flask_session.dynamodb',
 'flask_session.filesystem',
 'flask_session.memcached',
 'flask_session.mongodb',
 'flask_session.redis',
 'flask_session.sqlalchemy']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

install_requires = \
['flask>=2.2', 'msgspec>=0.18.6', 'cachelib']

extras_require = \
{'all': ['Flask-Session[cachelib, memcached, mongodb, redis, sqlalchemy]'],
 'cachelib': ['cachelib>=0.10.2'],
 'memcached': ['pymemcache'],
 'mongodb': ['pymongo>=4.6.2'],
 'redis': ['redis>=5.0.3'],
 'sqlalchemy': ['flask-sqlalchemy>=3.0.5']}

setup(name='Flask-Session',
      version='0.8.0',
      description='Server-side session support for Flask',
      author=None,
      author_email='Shipeng Feng <fsp261@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.8',
     )
